### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by beastybeast** [copy/jslzjb-k#2]
Hi

In line 99 I always get this error during compress and the length returned by the compress function is actually bigger then the source and destination Uint8Array size.

Something is wrong?

/Benny

**Comment by copy** [comment]
Sorry about the delay, I forgot about this issue.

This can happen if your data is not compressible, for example if it's very short. You can check with another implementation, for example this one: https://github.com/cscott/lzjb (this one compresses slightly better, but you get a ballpark for compressibility).

I've removed the assertion and updated the documentation. I'd recommend checking the return value of `compress` like [this](https://github.com/copy/jslzjb-k/blob/d854276960d5af1dce106e01d5c0290526f69c66/test-lzjb.js#L22-L26).
